plugins {
    id 'com.android.library'
    id 'maven-publish'
}

android {
	namespace = "com.jiangdg.uvccamera"
	compileSdkVersion rootProject.ext.versionCompiler
	
	publishing {
		singleVariant('release') {
			withSourcesJar()
		}
	}

	packagingOptions {
		pickFirst 'lib/**/*.so'
	}

	compileOptions {
		sourceCompatibility rootProject.ext.javaSourceCompatibility
		targetCompatibility rootProject.ext.javaTargetCompatibility
	}

	defaultConfig {
		minSdkVersion rootProject.ext.minSdkVersion
		ndkVersion rootProject.ext.ndkVersion

		ndk {
			// Exclude x86 and x86_64 until update libjpeg-turbo
			abiFilters 'armeabi-v7a', 'arm64-v8a'
		}
	}


	buildTypes {
		release {
			minifyEnabled false
			proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.txt'
		}
	}

	externalNativeBuild {
		ndkBuild {
			path 'src/main/jni/Android.mk'
		}
	}
	lint {
		abortOnError false
		checkReleaseBuilds false
		disable 'MissingTranslation'
		targetSdk 36
	}
	testOptions {
		targetSdk 36
	}
}

dependencies {
	implementation fileTree(dir: new File(buildDir, 'libs'), include: '*.jar')
	implementation "androidx.appcompat:appcompat:${androidXVersion}"
	implementation 'com.elvishew:xlog:1.11.1'
}

afterEvaluate {
    publishing {
        publications {
            release(MavenPublication) {
                from components.release
                groupId = 'com.github.ernestp'
                artifactId = 'libuvc'
                version = rootProject.ext.versionNameString
            }
        }
    }
}
